export const LOGIN_SUCCESS = "LOGIN_SUCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";

export const FETCH_LOGIN_DETAILS_SUCCESS = "FETCH_LOGIN_DETAILS_SUCESS";
export const FETCH_LOGIN_DETAILS_FAIL = "FETCH_LOGIN_DETAILS_FAIL";