export const FETCH_EDUCATION = 'FETCH_EDUCATION';
export const FETCH_EDUCATION_SUCCESS = "FETCH_EDUCATION_SUCCESS";
export const FETCH_EDUCATION_FAIL = "FETCH_EDUCATION_FAIL";

export const CREATE_EDUCATION = 'CREATE_EDUCATION';
export const CREATE_EDUCATION_SUCCESS = "CREATE_EDUCATION_SUCCESS";
export const CREATE_EDUCATION_FAIL = "CREATE_EDUCATION_FAIL";

export const UPDATE_EDUCATION = 'UPDATE_EDUCATION';
export const UPDATE_EDUCATION_SUCCESS = "UPDATE_EDUCATION_SUCCESS";
export const UPDATE_EDUCATION_FAIL = "UPDATE_EDUCATION_FAIL";

export const DELETE_EDUCATION = 'DELETE_EDUCATION';
export const DELETE_EDUCATION_SUCCESS = "DELETE_EDUCATION_SUCCESS";
export const DELETE_EDUCATION_FAIL = "DELETE_EDUCATION_FAIL";